"""create slide_engagement table

Revision ID: 62bb8aab01db
Revises: a70bf6d73a1e
Create Date: 2026-10-04

Hand-written to contain ONLY the slide_engagement table. The autogenerated
version swept up unrelated drift on at_risk_flags / common_mastery_quizzes /
knowledge_document_versions — those are intentionally excluded here.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "62bb8aab01db"
down_revision = "a70bf6d73a1e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "slide_engagement",
        sa.Column("id", sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("subtopic_id", sa.Uuid(), nullable=False),
        sa.Column("slide_index", sa.Integer(), nullable=False),
        sa.Column("seconds_active", sa.Integer(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["student_id"], ["student_profiles.id"]),
        sa.ForeignKeyConstraint(["subtopic_id"], ["subtopics.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_slide_engagement_student_id", "slide_engagement", ["student_id"])
    op.create_index("ix_slide_engagement_subtopic_id", "slide_engagement", ["subtopic_id"])
    op.create_index("ix_slide_engagement_recorded_at", "slide_engagement", ["recorded_at"])


def downgrade() -> None:
    op.drop_index("ix_slide_engagement_recorded_at", table_name="slide_engagement")
    op.drop_index("ix_slide_engagement_subtopic_id", table_name="slide_engagement")
    op.drop_index("ix_slide_engagement_student_id", table_name="slide_engagement")
    op.drop_table("slide_engagement")
