"""create education platform schema

Revision ID: c78987b61e05
Revises:
Create Date: 2026-08-09 13:55:11.597321
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str | Sequence[str] | None = "c78987b61e05"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institutions",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="institution_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
        sa.UniqueConstraint("name", name=op.f("uq_institutions_name")),
    )
    op.create_table(
        "academic_periods",
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planned",
                "active",
                "closed",
                "archived",
                name="academic_period_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_academic_periods_institution_id_institutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_academic_periods")),
        sa.UniqueConstraint("institution_id", "name", name="uq_academic_periods_institution_name"),
    )
    with op.batch_alter_table("academic_periods", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_academic_periods_institution_id"), ["institution_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_academic_periods_status"), ["status"], unique=False)
        batch_op.create_index(
            "uq_academic_periods_one_active_per_institution",
            ["institution_id"],
            unique=True,
            sqlite_where=sa.text("status = 'active'"),
        )

    op.create_table(
        "grades",
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_grades_institution_id_institutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grades")),
        sa.UniqueConstraint("institution_id", "name", name="uq_grades_institution_name"),
    )
    with op.batch_alter_table("grades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_grades_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "subjects",
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_subjects_institution_id_institutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subjects")),
        sa.UniqueConstraint("institution_id", "code", name="uq_subjects_institution_code"),
    )
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_subjects_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "provisioned",
                "active",
                "deactivated",
                "archived",
                name="user_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_users_institution_id_institutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("institution_id", "email", name="uq_users_institution_email"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_institution_id"), ["institution_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_users_status"), ["status"], unique=False)

    op.create_table(
        "audit_events",
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_events_actor_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_audit_events_institution_id_institutions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_events_actor_user_id"), ["actor_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_audit_events_institution_id"), ["institution_id"], unique=False
        )

    op.create_table(
        "period_grades",
        sa.Column("academic_period_id", sa.Uuid(), nullable=False),
        sa.Column("grade_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_period_id"],
            ["academic_periods.id"],
            name=op.f("fk_period_grades_academic_period_id_academic_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["grade_id"], ["grades.id"], name=op.f("fk_period_grades_grade_id_grades")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_period_grades")),
        sa.UniqueConstraint("academic_period_id", "grade_id", name="uq_period_grades_period_grade"),
    )
    with op.batch_alter_table("period_grades", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_period_grades_academic_period_id"), ["academic_period_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_period_grades_grade_id"), ["grade_id"], unique=False)

    op.create_table(
        "refresh_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_refresh_sessions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
    )
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_refresh_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_refresh_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "student_profiles",
        sa.Column("institution_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("student_identifier", sa.String(length=100), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "inactive", "archived", name="student_profile_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_student_profiles_institution_id_institutions"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_student_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_profiles")),
        sa.UniqueConstraint(
            "institution_id",
            "student_identifier",
            name="uq_student_profiles_institution_identifier",
        ),
    )
    with op.batch_alter_table("student_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_profiles_institution_id"), ["institution_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_student_profiles_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "uq_student_profiles_user_id",
            ["user_id"],
            unique=True,
            sqlite_where=sa.text("user_id IS NOT NULL"),
        )

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("administrator", "teacher", "student", name="role_name", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_roles")),
        sa.UniqueConstraint("user_id", "role", name="uq_user_roles_user_role"),
    )
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_roles_user_id"), ["user_id"], unique=False)

    op.create_table(
        "grade_subject_offerings",
        sa.Column("period_grade_id", sa.Uuid(), nullable=False),
        sa.Column("subject_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["period_grade_id"],
            ["period_grades.id"],
            name=op.f("fk_grade_subject_offerings_period_grade_id_period_grades"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
            name=op.f("fk_grade_subject_offerings_subject_id_subjects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grade_subject_offerings")),
        sa.UniqueConstraint(
            "period_grade_id", "subject_id", name="uq_grade_subject_offerings_period_grade_subject"
        ),
    )
    with op.batch_alter_table("grade_subject_offerings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_grade_subject_offerings_period_grade_id"),
            ["period_grade_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_grade_subject_offerings_subject_id"), ["subject_id"], unique=False
        )

    op.create_table(
        "sections",
        sa.Column("period_grade_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["period_grade_id"],
            ["period_grades.id"],
            name=op.f("fk_sections_period_grade_id_period_grades"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sections")),
        sa.UniqueConstraint("period_grade_id", "name", name="uq_sections_period_grade_name"),
    )
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sections_period_grade_id"), ["period_grade_id"], unique=False
        )

    op.create_table(
        "student_grade_enrollments",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("academic_period_id", sa.Uuid(), nullable=False),
        sa.Column("period_grade_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "withdrawn", name="enrollment_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_period_id"],
            ["academic_periods.id"],
            name=op.f("fk_student_grade_enrollments_academic_period_id_academic_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["period_grade_id"],
            ["period_grades.id"],
            name=op.f("fk_student_grade_enrollments_period_grade_id_period_grades"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_student_grade_enrollments_section_id_sections"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.id"],
            name=op.f("fk_student_grade_enrollments_student_id_student_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_grade_enrollments")),
    )
    with op.batch_alter_table("student_grade_enrollments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_grade_enrollments_academic_period_id"),
            ["academic_period_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_student_grade_enrollments_period_grade_id"),
            ["period_grade_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_student_grade_enrollments_section_id"), ["section_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_grade_enrollments_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_grade_enrollments_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "uq_student_grade_enrollments_active",
            ["student_id", "academic_period_id"],
            unique=True,
            sqlite_where=sa.text("status = 'active'"),
        )

    op.create_table(
        "teaching_assignments",
        sa.Column("teacher_user_id", sa.Uuid(), nullable=False),
        sa.Column("academic_period_id", sa.Uuid(), nullable=False),
        sa.Column("grade_subject_offering_id", sa.Uuid(), nullable=False),
        sa.Column("section_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "ended", name="teaching_assignment_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["academic_period_id"],
            ["academic_periods.id"],
            name=op.f("fk_teaching_assignments_academic_period_id_academic_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["grade_subject_offering_id"],
            ["grade_subject_offerings.id"],
            name=op.f("fk_teaching_assignments_grade_subject_offering_id_grade_subject_offerings"),
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
            name=op.f("fk_teaching_assignments_section_id_sections"),
        ),
        sa.ForeignKeyConstraint(
            ["teacher_user_id"],
            ["users.id"],
            name=op.f("fk_teaching_assignments_teacher_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teaching_assignments")),
    )
    with op.batch_alter_table("teaching_assignments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_teaching_assignments_academic_period_id"),
            ["academic_period_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_teaching_assignments_grade_subject_offering_id"),
            ["grade_subject_offering_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_teaching_assignments_section_id"), ["section_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_teaching_assignments_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_teaching_assignments_teacher_user_id"), ["teacher_user_id"], unique=False
        )
        batch_op.create_index(
            "uq_teaching_assignments_with_section",
            ["teacher_user_id", "grade_subject_offering_id", "section_id"],
            unique=True,
            sqlite_where=sa.text("section_id IS NOT NULL"),
        )
        batch_op.create_index(
            "uq_teaching_assignments_without_section",
            ["teacher_user_id", "grade_subject_offering_id"],
            unique=True,
            sqlite_where=sa.text("section_id IS NULL"),
        )

    op.create_table(
        "topics",
        sa.Column("grade_subject_offering_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grade_subject_offering_id"],
            ["grade_subject_offerings.id"],
            name=op.f("fk_topics_grade_subject_offering_id_grade_subject_offerings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topics")),
        sa.UniqueConstraint(
            "grade_subject_offering_id", "sequence", name="uq_topics_offering_sequence"
        ),
        sa.UniqueConstraint("grade_subject_offering_id", "slug", name="uq_topics_offering_slug"),
    )
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_topics_grade_subject_offering_id"),
            ["grade_subject_offering_id"],
            unique=False,
        )

    op.create_table(
        "student_subject_enrollments",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("grade_enrollment_id", sa.Uuid(), nullable=False),
        sa.Column("grade_subject_offering_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "withdrawn", name="enrollment_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["grade_enrollment_id"],
            ["student_grade_enrollments.id"],
            name=op.f(
                "fk_student_subject_enrollments_grade_enrollment_id_student_grade_enrollments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["grade_subject_offering_id"],
            ["grade_subject_offerings.id"],
            name=op.f(
                "fk_student_subject_enrollments_grade_subject_offering_id_grade_subject_offerings"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.id"],
            name=op.f("fk_student_subject_enrollments_student_id_student_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_subject_enrollments")),
    )
    with op.batch_alter_table("student_subject_enrollments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_student_subject_enrollments_grade_enrollment_id"),
            ["grade_enrollment_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_student_subject_enrollments_grade_subject_offering_id"),
            ["grade_subject_offering_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_student_subject_enrollments_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_student_subject_enrollments_student_id"), ["student_id"], unique=False
        )
        batch_op.create_index(
            "uq_student_subject_enrollments_active",
            ["student_id", "grade_subject_offering_id"],
            unique=True,
            sqlite_where=sa.text("status = 'active'"),
        )

    op.create_table(
        "subtopics",
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"], ["topics.id"], name=op.f("fk_subtopics_topic_id_topics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subtopics")),
        sa.UniqueConstraint("topic_id", "sequence", name="uq_subtopics_topic_sequence"),
        sa.UniqueConstraint("topic_id", "slug", name="uq_subtopics_topic_slug"),
    )
    with op.batch_alter_table("subtopics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_subtopics_topic_id"), ["topic_id"], unique=False)

    op.create_table(
        "common_mastery_quizzes",
        sa.Column("subtopic_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subtopic_id"],
            ["subtopics.id"],
            name=op.f("fk_common_mastery_quizzes_subtopic_id_subtopics"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_common_mastery_quizzes")),
        sa.UniqueConstraint("subtopic_id", name="uq_common_mastery_quizzes_subtopic"),
    )
    with op.batch_alter_table("common_mastery_quizzes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_common_mastery_quizzes_subtopic_id"), ["subtopic_id"], unique=False
        )

    op.create_table(
        "learning_outcomes",
        sa.Column("subtopic_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subtopic_id"],
            ["subtopics.id"],
            name=op.f("fk_learning_outcomes_subtopic_id_subtopics"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_outcomes")),
        sa.UniqueConstraint("subtopic_id", "code", name="uq_learning_outcomes_subtopic_code"),
    )
    with op.batch_alter_table("learning_outcomes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_outcomes_subtopic_id"), ["subtopic_id"], unique=False
        )

    op.create_table(
        "questions",
        sa.Column("subtopic_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subtopic_id"], ["subtopics.id"], name=op.f("fk_questions_subtopic_id_subtopics")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_questions")),
    )
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_questions_subtopic_id"), ["subtopic_id"], unique=False)

    op.create_table(
        "source_materials",
        sa.Column("subtopic_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "published", "archived", name="source_material_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["subtopic_id"],
            ["subtopics.id"],
            name=op.f("fk_source_materials_subtopic_id_subtopics"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_materials")),
        sa.UniqueConstraint("subtopic_id", "slug", name="uq_source_materials_subtopic_slug"),
    )
    with op.batch_alter_table("source_materials", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_source_materials_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_source_materials_subtopic_id"), ["subtopic_id"], unique=False
        )

    op.create_table(
        "question_versions",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "multiple_choice",
                "true_false",
                "matching",
                "numeric",
                name="question_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "difficulty",
            sa.Enum("easy", "medium", "hard", name="question_difficulty", native_enum=False),
            nullable=True,
        ),
        sa.Column("marks", sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "lifecycle_status",
            sa.Enum(
                "draft", "published", "archived", name="question_version_status", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
            name=op.f("fk_question_versions_question_id_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_versions")),
        sa.UniqueConstraint(
            "question_id", "version_number", name="uq_question_versions_question_version"
        ),
    )
    with op.batch_alter_table("question_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_versions_lifecycle_status"), ["lifecycle_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_versions_question_id"), ["question_id"], unique=False
        )

    op.create_table(
        "quiz_versions",
        sa.Column("quiz_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "lifecycle_status",
            sa.Enum(
                "draft",
                "ready",
                "released",
                "archived",
                name="quiz_version_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("max_attempts", sa.Integer(), nullable=True),
        sa.Column(
            "result_release_mode",
            sa.Enum(
                "immediate", "admin_release", name="quiz_result_release_mode", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"],
            ["common_mastery_quizzes.id"],
            name=op.f("fk_quiz_versions_quiz_id_common_mastery_quizzes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_versions")),
        sa.UniqueConstraint("quiz_id", "version_number", name="uq_quiz_versions_quiz_version"),
    )
    with op.batch_alter_table("quiz_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_versions_lifecycle_status"), ["lifecycle_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quiz_versions_quiz_id"), ["quiz_id"], unique=False)

    op.create_table(
        "source_material_versions",
        sa.Column("source_material_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column(
            "lifecycle_status",
            sa.Enum(
                "draft",
                "processing",
                "ready",
                "published",
                "failed",
                "superseded",
                "archived",
                name="source_material_version_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=True),
        sa.Column("content_format", sa.String(length=50), nullable=False),
        sa.Column("blob_object_key", sa.String(length=500), nullable=True),
        sa.Column("blob_content_type", sa.String(length=100), nullable=True),
        sa.Column("checksum", sa.String(length=64), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_material_id"],
            ["source_materials.id"],
            name=op.f("fk_source_material_versions_source_material_id_source_materials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_material_versions")),
        sa.UniqueConstraint(
            "source_material_id",
            "version_number",
            name="uq_source_material_versions_material_version",
        ),
    )
    with op.batch_alter_table("source_material_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_source_material_versions_lifecycle_status"),
            ["lifecycle_status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_source_material_versions_source_material_id"),
            ["source_material_id"],
            unique=False,
        )
        batch_op.create_index(
            "uq_source_material_versions_one_published",
            ["source_material_id"],
            unique=True,
            sqlite_where=sa.text("lifecycle_status = 'published'"),
        )

    op.create_table(
        "question_answer_keys",
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("correct_option_label", sa.String(length=10), nullable=True),
        sa.Column("correct_boolean", sa.Boolean(), nullable=True),
        sa.Column("correct_numeric", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("correct_mapping", sa.JSON(), nullable=True),
        sa.Column("scoring_rubric", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_question_answer_keys_question_version_id_question_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_answer_keys")),
    )
    with op.batch_alter_table("question_answer_keys", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_answer_keys_question_version_id"),
            ["question_version_id"],
            unique=True,
        )

    op.create_table(
        "question_options",
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=10), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_question_options_question_version_id_question_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_options")),
        sa.UniqueConstraint(
            "question_version_id", "label", name="uq_question_options_version_label"
        ),
    )
    with op.batch_alter_table("question_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_options_question_version_id"),
            ["question_version_id"],
            unique=False,
        )

    op.create_table(
        "question_outcome_tags",
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("learning_outcome_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["learning_outcome_id"],
            ["learning_outcomes.id"],
            name=op.f("fk_question_outcome_tags_learning_outcome_id_learning_outcomes"),
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_question_outcome_tags_question_version_id_question_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_outcome_tags")),
        sa.UniqueConstraint(
            "question_version_id",
            "learning_outcome_id",
            name="uq_question_outcome_tags_version_outcome",
        ),
    )
    with op.batch_alter_table("question_outcome_tags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_outcome_tags_learning_outcome_id"),
            ["learning_outcome_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_question_outcome_tags_question_version_id"),
            ["question_version_id"],
            unique=False,
        )

    op.create_table(
        "quiz_attempts",
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("quiz_version_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "not_started",
                "in_progress",
                "submitted",
                "expired",
                "scored",
                "released",
                "held",
                name="quiz_attempt_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("score_raw", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("score_percent", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_version_id"],
            ["quiz_versions.id"],
            name=op.f("fk_quiz_attempts_quiz_version_id_quiz_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["student_profiles.id"],
            name=op.f("fk_quiz_attempts_student_id_student_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_attempts")),
        sa.UniqueConstraint(
            "student_id",
            "quiz_version_id",
            "attempt_number",
            name="uq_quiz_attempts_student_version_number",
        ),
    )
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_quiz_version_id"), ["quiz_version_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_quiz_attempts_status"), ["status"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_quiz_attempts_student_id"), ["student_id"], unique=False
        )

    op.create_table(
        "quiz_items",
        sa.Column("quiz_version_id", sa.Uuid(), nullable=False),
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_quiz_items_question_version_id_question_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["quiz_version_id"],
            ["quiz_versions.id"],
            name=op.f("fk_quiz_items_quiz_version_id_quiz_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_items")),
        sa.UniqueConstraint(
            "quiz_version_id", "question_version_id", name="uq_quiz_items_version_question"
        ),
        sa.UniqueConstraint("quiz_version_id", "sequence", name="uq_quiz_items_version_sequence"),
    )
    with op.batch_alter_table("quiz_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_items_question_version_id"), ["question_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_items_quiz_version_id"), ["quiz_version_id"], unique=False
        )

    op.create_table(
        "quiz_material_bindings",
        sa.Column("quiz_version_id", sa.Uuid(), nullable=False),
        sa.Column("source_material_version_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_version_id"],
            ["quiz_versions.id"],
            name=op.f("fk_quiz_material_bindings_quiz_version_id_quiz_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_material_version_id"],
            ["source_material_versions.id"],
            name=op.f(
                "fk_quiz_material_bindings_source_material_version_id_source_material_versions"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_material_bindings")),
        sa.UniqueConstraint(
            "quiz_version_id",
            "source_material_version_id",
            name="uq_quiz_material_bindings_version_material",
        ),
    )
    with op.batch_alter_table("quiz_material_bindings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_material_bindings_quiz_version_id"),
            ["quiz_version_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_material_bindings_source_material_version_id"),
            ["source_material_version_id"],
            unique=False,
        )

    op.create_table(
        "quiz_releases",
        sa.Column("quiz_version_id", sa.Uuid(), nullable=False),
        sa.Column("window_starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("scheduled", "open", "closed", name="quiz_release_status", native_enum=False),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["quiz_version_id"],
            ["quiz_versions.id"],
            name=op.f("fk_quiz_releases_quiz_version_id_quiz_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["released_by_user_id"],
            ["users.id"],
            name=op.f("fk_quiz_releases_released_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_quiz_releases")),
    )
    with op.batch_alter_table("quiz_releases", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_quiz_releases_quiz_version_id"), ["quiz_version_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_quiz_releases_released_by_user_id"),
            ["released_by_user_id"],
            unique=False,
        )
        batch_op.create_index(batch_op.f("ix_quiz_releases_status"), ["status"], unique=False)

    op.create_table(
        "attempt_answers",
        sa.Column("attempt_id", sa.Uuid(), nullable=False),
        sa.Column("question_version_id", sa.Uuid(), nullable=False),
        sa.Column("selected_option_label", sa.String(length=10), nullable=True),
        sa.Column("selected_boolean", sa.Boolean(), nullable=True),
        sa.Column("selected_numeric", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column("selected_mapping", sa.JSON(), nullable=True),
        sa.Column("is_correct", sa.Boolean(), nullable=True),
        sa.Column("marks_awarded", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["quiz_attempts.id"],
            name=op.f("fk_attempt_answers_attempt_id_quiz_attempts"),
        ),
        sa.ForeignKeyConstraint(
            ["question_version_id"],
            ["question_versions.id"],
            name=op.f("fk_attempt_answers_question_version_id_question_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_answers")),
        sa.UniqueConstraint(
            "attempt_id", "question_version_id", name="uq_attempt_answers_attempt_question"
        ),
    )
    with op.batch_alter_table("attempt_answers", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attempt_answers_attempt_id"), ["attempt_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attempt_answers_question_version_id"),
            ["question_version_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attempt_answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attempt_answers_question_version_id"))
        batch_op.drop_index(batch_op.f("ix_attempt_answers_attempt_id"))

    op.drop_table("attempt_answers")
    with op.batch_alter_table("quiz_releases", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_releases_status"))
        batch_op.drop_index(batch_op.f("ix_quiz_releases_released_by_user_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_releases_quiz_version_id"))

    op.drop_table("quiz_releases")
    with op.batch_alter_table("quiz_material_bindings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_material_bindings_source_material_version_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_material_bindings_quiz_version_id"))

    op.drop_table("quiz_material_bindings")
    with op.batch_alter_table("quiz_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_items_quiz_version_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_items_question_version_id"))

    op.drop_table("quiz_items")
    with op.batch_alter_table("quiz_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_student_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_status"))
        batch_op.drop_index(batch_op.f("ix_quiz_attempts_quiz_version_id"))

    op.drop_table("quiz_attempts")
    with op.batch_alter_table("question_outcome_tags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_outcome_tags_question_version_id"))
        batch_op.drop_index(batch_op.f("ix_question_outcome_tags_learning_outcome_id"))

    op.drop_table("question_outcome_tags")
    with op.batch_alter_table("question_options", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_options_question_version_id"))

    op.drop_table("question_options")
    with op.batch_alter_table("question_answer_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_answer_keys_question_version_id"))

    op.drop_table("question_answer_keys")
    with op.batch_alter_table("source_material_versions", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_source_material_versions_one_published",
            sqlite_where=sa.text("lifecycle_status = 'published'"),
        )
        batch_op.drop_index(batch_op.f("ix_source_material_versions_source_material_id"))
        batch_op.drop_index(batch_op.f("ix_source_material_versions_lifecycle_status"))

    op.drop_table("source_material_versions")
    with op.batch_alter_table("quiz_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_quiz_versions_quiz_id"))
        batch_op.drop_index(batch_op.f("ix_quiz_versions_lifecycle_status"))

    op.drop_table("quiz_versions")
    with op.batch_alter_table("question_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_versions_question_id"))
        batch_op.drop_index(batch_op.f("ix_question_versions_lifecycle_status"))

    op.drop_table("question_versions")
    with op.batch_alter_table("source_materials", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_source_materials_subtopic_id"))
        batch_op.drop_index(batch_op.f("ix_source_materials_status"))

    op.drop_table("source_materials")
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_questions_subtopic_id"))

    op.drop_table("questions")
    with op.batch_alter_table("learning_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_outcomes_subtopic_id"))

    op.drop_table("learning_outcomes")
    with op.batch_alter_table("common_mastery_quizzes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_common_mastery_quizzes_subtopic_id"))

    op.drop_table("common_mastery_quizzes")
    with op.batch_alter_table("subtopics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subtopics_topic_id"))

    op.drop_table("subtopics")
    with op.batch_alter_table("student_subject_enrollments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_student_subject_enrollments_active", sqlite_where=sa.text("status = 'active'")
        )
        batch_op.drop_index(batch_op.f("ix_student_subject_enrollments_student_id"))
        batch_op.drop_index(batch_op.f("ix_student_subject_enrollments_status"))
        batch_op.drop_index(batch_op.f("ix_student_subject_enrollments_grade_subject_offering_id"))
        batch_op.drop_index(batch_op.f("ix_student_subject_enrollments_grade_enrollment_id"))

    op.drop_table("student_subject_enrollments")
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topics_grade_subject_offering_id"))

    op.drop_table("topics")
    with op.batch_alter_table("teaching_assignments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_teaching_assignments_without_section", sqlite_where=sa.text("section_id IS NULL")
        )
        batch_op.drop_index(
            "uq_teaching_assignments_with_section", sqlite_where=sa.text("section_id IS NOT NULL")
        )
        batch_op.drop_index(batch_op.f("ix_teaching_assignments_teacher_user_id"))
        batch_op.drop_index(batch_op.f("ix_teaching_assignments_status"))
        batch_op.drop_index(batch_op.f("ix_teaching_assignments_section_id"))
        batch_op.drop_index(batch_op.f("ix_teaching_assignments_grade_subject_offering_id"))
        batch_op.drop_index(batch_op.f("ix_teaching_assignments_academic_period_id"))

    op.drop_table("teaching_assignments")
    with op.batch_alter_table("student_grade_enrollments", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_student_grade_enrollments_active", sqlite_where=sa.text("status = 'active'")
        )
        batch_op.drop_index(batch_op.f("ix_student_grade_enrollments_student_id"))
        batch_op.drop_index(batch_op.f("ix_student_grade_enrollments_status"))
        batch_op.drop_index(batch_op.f("ix_student_grade_enrollments_section_id"))
        batch_op.drop_index(batch_op.f("ix_student_grade_enrollments_period_grade_id"))
        batch_op.drop_index(batch_op.f("ix_student_grade_enrollments_academic_period_id"))

    op.drop_table("student_grade_enrollments")
    with op.batch_alter_table("sections", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sections_period_grade_id"))

    op.drop_table("sections")
    with op.batch_alter_table("grade_subject_offerings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grade_subject_offerings_subject_id"))
        batch_op.drop_index(batch_op.f("ix_grade_subject_offerings_period_grade_id"))

    op.drop_table("grade_subject_offerings")
    with op.batch_alter_table("user_roles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_roles_user_id"))

    op.drop_table("user_roles")
    with op.batch_alter_table("student_profiles", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_student_profiles_user_id", sqlite_where=sa.text("user_id IS NOT NULL")
        )
        batch_op.drop_index(batch_op.f("ix_student_profiles_user_id"))
        batch_op.drop_index(batch_op.f("ix_student_profiles_institution_id"))

    op.drop_table("student_profiles")
    with op.batch_alter_table("refresh_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_refresh_sessions_token_hash"))

    op.drop_table("refresh_sessions")
    with op.batch_alter_table("period_grades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_period_grades_grade_id"))
        batch_op.drop_index(batch_op.f("ix_period_grades_academic_period_id"))

    op.drop_table("period_grades")
    with op.batch_alter_table("audit_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_events_institution_id"))
        batch_op.drop_index(batch_op.f("ix_audit_events_event_type"))
        batch_op.drop_index(batch_op.f("ix_audit_events_actor_user_id"))

    op.drop_table("audit_events")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_status"))
        batch_op.drop_index(batch_op.f("ix_users_institution_id"))

    op.drop_table("users")
    with op.batch_alter_table("subjects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_subjects_institution_id"))

    op.drop_table("subjects")
    with op.batch_alter_table("grades", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_grades_institution_id"))

    op.drop_table("grades")
    with op.batch_alter_table("academic_periods", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_academic_periods_one_active_per_institution",
            sqlite_where=sa.text("status = 'active'"),
        )
        batch_op.drop_index(batch_op.f("ix_academic_periods_status"))
        batch_op.drop_index(batch_op.f("ix_academic_periods_institution_id"))

    op.drop_table("academic_periods")
    op.drop_table("institutions")
    # ### end Alembic commands ###
